# Generated by Django 4.1.1 on 2022-10-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_news_preambule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='bode_as_markdown',
            new_name='body_as_markdown',
        ),
    ]
